### ISSUE TITLE
MADO CHE SBORO

### ISSUE THREAD

**Issue by mirochu** [Motorola104/Motorola104.github.io#1]
Ciao, mi volevo complimentare col suo sito web egregio signor Motorola.
È davvero ben fatto, molto "accogliente" e strutturato bene.
I file html sono scritti in modo pulito e mettendo i commenti dove andavano messi.
Amo anche la sezione "Mie Attività" dove si nota molto che lei è un gran fan di Minecraft, giuoco sviluppato dalla FAMOSSISSIMA software-house Mojang.
Unica pecca, nella sezione: "Dove siamo" il tema non viene rispettato ma per il resto tutto ok

**Comment by Motorola104** [comment]
CIao a te,grazie dei complimenti provvederò a migliorare ancora di più.
